apiVersion: v1
kind: Service
metadata:
    name: "go-hello-world"
    labels:
        app: "go-hello-world"
        password: "bXlzdXBlcnNlY3JldHBhc3N3b3Jk"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "go-hello-world"
